### ISSUE TITLE
How to implement HTTP Authorization?

### ISSUE THREAD

**Issue by sagikazarmark** [lstrojny/fxmlrpc#14]
Using the arguments I can implement XML-RPC server based authentication by passing username/password arguments to the call. How can I implement HTTP-based authentication?

Since the transport is a private property of the client I cannot access it, howerver I only want take care of an injected `ClientInterface`. So the actual question: If I have a Client object, how can I make it send HTTP Authorization header?

**Comment by OnkelTem** [comment]
@lstrojny Would you provide an example of HTTP authorization? It's not clear at all. With all these dozens of adapters and things...

**Comment by OnkelTem** [comment]
Let me be more descriptive.

This doesn't work:

```
use Http\Adapter\Guzzle6\Client;
use Http\Message\MessageFactory\DiactorosMessageFactory;

$httpClient = new GuzzleHttp\Client([
  'defaults' => [
    'auth' => ['username', 'password']
  ],
]);

$client = new fXmlRpc\Client(
  'http://endpoint',
  new fXmlRpc\Transport\HttpAdapterTransport(
    new DiactorosMessageFactory(),
    new Client($httpClient)
  )
);

$result = $client->call(...);
```

i.e. it doesn't log in.

**Comment by OnkelTem** [comment]
Ok, nevermind, I should have passed `auth` option to Guzzle Client directly:

```php
$httpClient = new GuzzleHttp\Client([
  'auth' => ['username', 'password']
]);
```

**Comment by sagikazarmark** [comment]
Yep, the last one is the latest structure. It depends on your Guzzle version.

**Comment by EdgarSedov** [comment]
Library client fXmlRpc/Client does not provide public methods to add custom headers for request, whicht makes it impossible to use it when u have to provide custom headers or their values which differs for each request
