### ISSUE TITLE
HTTP Transport decorator

### ISSUE THREAD

**Issue by sagikazarmark** [lstrojny/fxmlrpc#21]
Would be nice to have a decorator for HTTP transports, so that writting decorators is easier. Current use case: Authentication decorator, which sets some header in the constructor, otherwise it behaves like the underlying transport.

**Comment by lstrojny** [comment]
Yup, sounds good.

**Comment by sagikazarmark** [comment]
Well, if we are going to replace transports with ivory, this is going to be invalid.

**Comment by lstrojny** [comment]
Closing
