### ISSUE TITLE
Replace Transports with a http adapter

### ISSUE THREAD

**Issue by sagikazarmark** [lstrojny/fxmlrpc#23]
I know it is a big change/BC break, but I see no real need for maintaining a http adapter inside this package. [Here](https://github.com/egeloen/ivory-http-adapter) is a quite good HTTP adapter package, under heavy development, but stable enough to use. Geocoder 3 will be released using this under the hood.

What do you think?

**Comment by lstrojny** [comment]
Looks very interesting, I am also not particularly interested in maintaining that. I honestly don’t have the time right now to look into that but I will happily accept a pull request that introduces an implementation for Ivory.

**Comment by sagikazarmark** [comment]
Does that mean you accept a PR replacing the current implementation?
2015.01.27. 22:13 ezt írta ("Lars Strojny" <notifications@github.com>):

**Comment by lstrojny** [comment]
Probably an IvoryTransport implementing the TransportInterface is the easiest way to go now. Then we can deprecate the rest of the transports over time.

**Comment by sagikazarmark** [comment]
I send a PR for it then. When it gets merged, I create a major release PR
as well.

**Comment by sagikazarmark** [comment]
About supporting: I have some open source and some business applications relying on this package, so it is definitely my interest to have active support for it, even if it is me who provides the support.

**Comment by lstrojny** [comment]
Closing

**Comment by sagikazarmark** [comment]
What about this? We talked about having a default implementation with only support for http adapters, so that an extra layer can be removed.

Creating ssh compatible clients is not that hard and you have to create some implementation either way. So why complicate the core implementation?
