### ISSUE TITLE
Update HTTP Adapter usage

### ISSUE THREAD

**Issue by sagikazarmark** [lstrojny/fxmlrpc#40]
Currently the HttpAdapterInterface is used as a dependency in HttpAdapterTransport.

We could probably rely on PsrHttpAdapterInterface (introduced in 0.8 development branch) which is a parent of HttpAdapterInterface. However in this case we would have to construct Request objects instead of calling `$adapter->post`. It adds complexity, but allows users to use a wider set of implementations.

**Comment by lstrojny** [comment]
I feel that would be tolerable. What do you think?

**Comment by sagikazarmark** [comment]
Will open a PR for it.

**Comment by sagikazarmark** [comment]
I wait for the migration to php-http organization

**Comment by sagikazarmark** [comment]
This is already in progress in the new package.
