### ISSUE TITLE
final keyword on Client class?

### ISSUE THREAD

**Issue by mattzuba** [lstrojny/fxmlrpc#42]
Just curious as the reasoning behind this?  I'm using __call() as a workaround for this for the time being, but it'd be easier to just extend the class and avoid the extra overhead.

**Comment by lstrojny** [comment]
The idea is to not extend the Client class itself, but rather to decorate it by extending AbstractClientDecorator. Can you elaborate on your use case to see if it is something we are not supporting at the moment?

**Comment by mattzuba** [comment]
Thanks, I didn't pay attention to that class when I was looking things over.  Using that makes this issue null and void.  Thanks! :)

**Comment by robclancy** [comment]
Using `final` in any package ever to satisfy your own weird philosophies when there are zero security implicates is just... unbelievable.

**Comment by lstrojny** [comment]
@robclancy let’s agree to disagree and there are other implementations of an XML/RPC client you can use that might better align with your stance. I am also wondering if you really believe your comment would make me reconsider my stance or if you wanted to blow off steam. While I can understand the latter, this is not the place for it.

**Comment by robclancy** [comment]
Blow off steam obviously because someone using the `final` keyword in a retarded way making it so I need to copy paste code instead of extending like a normal person.
