### ISSUE TITLE
Wrong example for Guzzle 4+

### ISSUE THREAD

**Issue by kazip** [lstrojny/fxmlrpc#43]
The example for Guzzle 4+ is not working, because you need to use \Ivory\HttpAdapter\GuzzleHttpHttpAdapter instead of \Ivory\HttpAdapter\GuzzleHttpAdapter

**Comment by sagikazarmark** [comment]
@kazip Both fxmlrpc and ivory http adapter will be abandoned. The new organization for these packages:

https://github.com/fxmlrpc
https://github.com/php-http

However both package is under heavy development.

**Comment by sagikazarmark** [comment]
But feel free to submit a PR though
