### ISSUE TITLE
Create Release Including Fix From #36

### ISSUE THREAD

**Issue by kressaty** [lstrojny/fxmlrpc#44]
#36 fixed a large pain point when implementing this lib in an API SDK, and a release would allow usage of that via composer with ease.

**Comment by lstrojny** [comment]
Done, released 0.9.5

**Comment by kressaty** [comment]
Wooo thanks!

**Comment by kressaty** [comment]
One more request - please don't delete releases. That immediately breaks installation of anything with that release as a dependency.
