### ISSUE TITLE
Class 'Ivory\HttpAdapter\HttpAdapterFactory' not found

### ISSUE THREAD

**Issue by tomsommer** [lstrojny/fxmlrpc#45]
After upgrading to 0.9.5 from 0.9.4:

( ! ) Fatal error: Class 'Ivory\HttpAdapter\HttpAdapterFactory' not found in ..../vendor/lstrojny/fxmlrpc/src/fXmlRpc/Client.php on line 75

**Comment by lstrojny** [comment]
Can you add "egeloen/http-adapter": "0.6.*@dev" to your composer.json?

**Comment by lstrojny** [comment]
Closing, see #38 for details
