### ISSUE TITLE
Logging requests

### ISSUE THREAD

**Issue by piotrooo** [lstrojny/fxmlrpc#47]
What do you think about implement method like `__getLastRequest` and `__getLastResponse` - like in `SoapClient` - to fast returning raw XML. Now you couldn't look for these info.

What case?

```php
$client = new Client($url);
$result = $client->call('Execute', [1, 2, 3]);
print_t($client->getLastRequest());
```

**Comment by lstrojny** [comment]
What type would {{getLastRequest()}} or {{getLastResponse()}} return?

**Comment by piotrooo** [comment]
I think this should be string. Thus you can use on it any XML formatter.

**Comment by lstrojny** [comment]
Ah, makes sense. Here are my thoughts:

 - Adding getResponse/getRequest to the Client would require broadening the ClientInterface which I don’t think makes sense
 - The perfect place to intercept request and response is on the transport level where you pass a string and it returns a string

So: implementing your functionality as a decorator to the transport would work. Something like this:

``php
namespace fXmlRpc\Transport\TransportRecorder;

use fXmlRpc\Transport\TransportInterface;

class Recorder implements TransportInterface
{
    private $transport;
    private $lastRequest;
    private $lastResponse;

    public function __construct(TransportInterface $transport)
    {
        $this->transport = $transport;
    }

    public function send($endpoint, $payload)
    {
        return $this->lastResponse = $this->transport->send($endpoint, $this->lastRequest = $payload);
    }

    public function getLastRequest()
    {
        return $this->lastRequest;
    }

    public function getLastResponse()
    {
        return $this->lastResponse;
    }
}
```

Usage would look like that:
```php
use fXmlRpc\Client\Client;
use fXmlRpc\Transport\TransportRecorder;
use fXmlRpc\Transport\Recorder;
use fXmlRpc\Transport\HttpAdapterTransport;

$recorder = new Recorder(new HttpAdapterTransport(…));
$client = new Client('http://my-endpoint.com', $recorder);
$client->call('my.method');

$recorder->getLastRequest();
$recorder->getLastResponse();
```

Does that look like a solution to your problem?

**Comment by piotrooo** [comment]
Yep, I think it's the best solution. I'll try to check this tomorrow and add PR for this issue if welcome.

**Comment by piotrooo** [comment]
I think we can close this issue.
