### ISSUE TITLE
Explicit empty()

### ISSUE THREAD

**Issue by lstrojny** [lstrojny/fxmlrpc#50]
see https://scrutinizer-ci.com/g/lstrojny/fxmlrpc/inspections/2b1ee0c2-8a24-4e4e-a56d-6d5a33da5ead/issues/files/src/fXmlRpc/Serializer/XmlWriterSerializer.php?status=existing&orderField=path&order=asc#inspectioncomment-954963074

**Comment by piotrooo** [comment]
IMHO, this should be checked by `empty` function, as is in this propose.
