### ISSUE TITLE
Non-XML response returns null, no way to access response

### ISSUE THREAD

**Issue by bslinger** [lstrojny/fxmlrpc#51]
I've just run into a situation where under certain circumstances the response coming back from an (alleged) XMLRPC server is not XML, but simply a string containing an error message. \fXmlRpc\Client::call currently just returns null from this request, but ideally it would throw an exception and have some way to get access to the string that came through in the response.

I understand that you might want to assume the URL being called will always return XML, though having some way to handle the cases when a URL is wrong might be handy. If you can suggest some other way to handle this, I'm open to ideas.

(It's a Magento store, in case you're interested, and the error occurs in certain versions where the URL for the XMLRPC interface has to be slightly tweaked)

**Comment by piotrooo** [comment]
For me this proposition is ok. In documentation (http://xmlrpc.scripting.com/spec.html) writes the response should contains only XML, so parser should detect that response is XML otherwise throw exception.

**Comment by lstrojny** [comment]
Throwing an exception makes indeed perfect sense.

**Comment by piotrooo** [comment]
I think this issue can be closed.
