### ISSUE TITLE
Confusing $isFault in Client

### ISSUE THREAD

**Issue by piotrooo** [lstrojny/fxmlrpc#53]
Why `Client` class has logic responsible for throwing exception when server return fault? It's little confusing for me, this is not responsibility of this class.

For me this exception should be thrown by parsers. And passing by reference could be removed.

For class `NativeParser` [line](https://github.com/lstrojny/fxmlrpc/blob/master/src/fXmlRpc/Parser/NativeParser.php#L80) could be changed for:

```php
throw ResponseException::fault($result);
```

For class `XmlReaderParser` [line](https://github.com/lstrojny/fxmlrpc/blob/master/src/fXmlRpc/Parser/XmlReaderParser.php#L130) could be set as internal variable and after all parsed document checked is fault was encountered and then throw exception.

**Comment by lstrojny** [comment]
Sounds like a good refactoring, agreed.

**Comment by piotrooo** [comment]
merged #57
