### ISSUE TITLE
Uncaught RuntimeException: Puli Factory is not available

### ISSUE THREAD

**Issue by cozmy** [lstrojny/fxmlrpc#61]
I've ran into `Fatal error: Uncaught RuntimeException: Puli Factory is not available in /localhost/vendor/php-http/discovery/src/ClassDiscovery.php:32` after installing your library via `composer require lstrojny/fxmlrpc` and trying to run the basic example:

```<?php
require_once dirname(__FILE__) . '/vendor/autoload.php';

$client = new \fXmlRpc\Client('http://endpoint.com');
$client->call('remoteMethod', array('arg1', true));
```

It seems that `PULI_FACTORY_CLASS` is not available. Any ideas on how to fix this issue?

**Comment by lstrojny** [comment]
No idea really. Can you check with the puli project?
