### ISSUE TITLE
Make zendframework/zend-diactoros, php-http/message and php-http/guzzle6-adapter dependencies

### ISSUE THREAD

**Issue by tomsommer** [lstrojny/fxmlrpc#62]
Seriously, it's so confusing that this package doesn't "just work". 

Make zendframework/zend-diactoros, php-http/message and php-http/guzzle6-adapter dependencies please, so that if one removes fxmlrpc, these are also removed. It just makes no sense not to.

**Comment by sagikazarmark** [comment]
The point in using an abstraction in the library is that you can use whichever HTTP client you want. For example if your application relies on Guzzle 5 you wouldn't be able to install this package if Guzzle 6 was a dependency. The other advantage is that you don't need a bunch of clients to be installed. What's really annoying is when 5 different packages install 5 different HTTP clients as dependencies.

It may add some complexity to the installation process, but it comes with a few advantages too which worth it IMO.

**Comment by lstrojny** [comment]
@tomsommer I agree with the sentiment, I find the current state of usability of PSR-7 can be improved but if I have to deal with some usability problems and get an HTTP client standard in exchange I am willing do to that trade off.
