### ISSUE TITLE
Use php-cs-fixer

### ISSUE THREAD

**Issue by piotrooo** [lstrojny/fxmlrpc#64]
@lstrojny what do you think about fix all code (src and tests) via **php-cs-fixer** using `PSR-2` standard?

I think this will be good practice and make code more beautiful (now is very good, but can be better as allways :smile:) than now.

Command should looks:

```
php-cs-fixer fix src/ --level=psr2
```

Links to **php-cs-fixer** plugin:

[https://github.com/FriendsOfPHP/PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer)
[http://cs.sensiolabs.org/](http://cs.sensiolabs.org/)

**Comment by lstrojny** [comment]
I ran it and the fixes are very small / debatable. Not seeing any value right now.
