### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by amirkoklan** [lstrojny/fxmlrpc#67]
Hello,

I have manually downloaded it and played and looks very good in terms of speed and now I want to install it into my project. (vendor Folder)

I did not quite get how can I install it ? there is no composer installation for the project ?

**Comment by lstrojny** [comment]
I tried to make the installation process more explicit, does it help?

https://github.com/lstrojny/fxmlrpc#installation

**Comment by amirkoklan** [comment]
Absolutely!

Thanks a lot
