### ISSUE TITLE
zend-diactoros is abandoned

### ISSUE THREAD

**Issue by tomsommer** [lstrojny/fxmlrpc#76]
zend-diactoros is abandoned, alternatives should be recommended

**Comment by EvilKarter** [comment]
https://github.com/laminas/laminas-diactoros

All zendframework packages were moved to laminas...
Have you an plan to migrate the packages?

**Comment by mfadul24** [comment]
Hi there. I've created a short PR that cover this issue too. https://github.com/lstrojny/fxmlrpc/pull/86 I would appreciate a review.

**Comment by lstrojny** [comment]
Closing now
