### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by VincentLanglet** [lstrojny/fxmlrpc#80]
Hi,

I saw that the requirement in `composer.json` is `~7.1`.
Any plan to support php 8 ? What are the blockers ?

Thanks.

**Comment by lstrojny** [comment]
Haven’t looked at all into support PHP 8.0 yet, so no idea. Can’t imagine it to be terribly hard to achieve so if anybody wants to get a PR rolling, help is very welcome!

**Comment by VincentLanglet** [comment]
Thanks @lstrojny

I'm trying https://github.com/lstrojny/fxmlrpc/pull/81
But the travis ci is not triggering...

**Comment by georanma** [comment]
@lstrojny happy to make a start. To proceed, we would need to update [InterNations/kodierungsregelwerksammlung](https://github.com/InterNations/kodierungsregelwerksammlung). 
Running the unit tests with php8 on that library throws a fatal error. I see the package is for codesniffs, but Im not sure I know enough about the context to put in a fix for the error. 

`Fatal error: Cannot use "parent" when current class scope has no parent in /app/tests/InterNations/Waste/Fixtures/PhpUnit/PhpUnitStaticallyCalledMethodsSniffFixtureTest.php on line 14
`

**Comment by Ultimater** [comment]
I use a package that relies on this package.
I can use `composer install --ignore-platform-reqs` and this package works for me on PHP 8, at least for my use case.

What's holding this package back from getting to PHP 8?

**Comment by Ultimater** [comment]
I commented on the PR here:
https://github.com/lstrojny/fxmlrpc/pull/81

Need a release for the PR...

**Comment by VincentLanglet** [comment]
This package is just abandoned @Ultimater

**Comment by VincentLanglet** [comment]
Desesperate ping, @lstrojny

**Comment by Sander-Toonen** [comment]
Thank you for the php8 support, can you please tag a new version?

**Comment by VincentLanglet** [comment]
> Thank you for the php8 support, can you please tag a new version?

0.20.0 was created
